### ISSUE TITLE
Cannot install on community 2.3.1

### ISSUE THREAD

**Issue by jzzaj** [interjar/configurable-child-visibility#10]
I tried to install on community 2.3.1 using composer and get these errors:

`
 Problem 1
    - Conclusion: remove magento/product-community-edition 2.3.1
    - Conclusion: don't install magento/product-community-edition 2.3.1
    - Installation request for interjar/module-configurable-child-visibility ^0.6.2 -> satisfiable by interjar/module-configurable-                                                child-visibility[0.6.2].
    - Installation request for magento/product-community-edition 2.3.1 -> satisfiable by magento/product-community-edition[2.3.1].
    - magento/product-community-edition 2.3.1 requires magento/framework 102.0.1 -> satisfiable by magento/framework[102.0.1].
    - Can only install one of: magento/framework[101.0.0, 102.0.1].
    - Can only install one of: magento/framework[102.0.1, 101.0.0].
    - Can only install one of: magento/framework[102.0.1, 101.0.0].
    - interjar/module-configurable-child-visibility 0.6.2 requires magento/framework 101.* -> satisfiable by magento/framework[101.                                                0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.4, 101.0.5, 101.0.6, 101.0.7, 101.0.8].
    - magento/framework 101.0.1 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-red                                                is-session-abstract[v1.3.4].
    - magento/framework 101.0.2 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-red                                                is-session-abstract[v1.3.4].
    - magento/framework 101.0.3 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-red                                                is-session-abstract[v1.3.4].
    - magento/framework 101.0.4 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-red                                                is-session-abstract[v1.3.4].
    - magento/framework 101.0.5 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-red                                                is-session-abstract[v1.3.4].
    - magento/framework 101.0.6 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-red                                                is-session-abstract[v1.3.4].
    - magento/framework 101.0.7 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-red                                                is-session-abstract[v1.3.4].
    - magento/framework 101.0.8 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-red                                                is-session-abstract[v1.3.4].
    - Conclusion: don't install colinmollenhour/php-redis-session-abstract v1.3.4
`
Any ideas? thanks.

**Comment by hardik-mamis** [comment]
I am also having issue installing on Magento 2.3.3 via composer. Adding error below. We've specified php  version in composer to use 7.2 which does not meet with requirements specified in the composer.json of this package.
![composer_install_error](https://user-images.githubusercontent.com/38927710/69312280-939c5780-0c82-11ea-9a6c-b6af0597a444.png)
