### ISSUE TITLE
Composer not updated

### ISSUE THREAD

**Issue by luuksuijkerbuijk** [interjar/configurable-child-visibility#13]
When I try to install the newest version (0.6.4) for a Magento 2.3 project, composer tells:

  [InvalidArgumentException]                                                                        
  Could not find package interjar/module-configurable-child-visibility in a version matching 0.6.4

Could you update composer?

**Comment by adamj88** [comment]
@luuksuijkerbuijk packagist is now showing v0.6.4 - https://packagist.org/packages/interjar/module-configurable-child-visibility
