### ISSUE TITLE
Bug on Magento2.3.5

### ISSUE THREAD

**Issue by grazianodimaio** [interjar/configurable-child-visibility#18]
Hello!

Just upgraded from 2.2.8 to 2.3.5

[2020-09-16 13:21:36] main.CRITICAL: 
Type Error occurred when creating object: Interjar\ConfigurableChildVisibility\Plugin\Model\ResourceModel\Attribute\InStockOptionSelectBuilder, Too few arguments to function Magento\ConfigurableProduct\Plugin\Model\ResourceModel\Attribute\InStockOptionSelectBuilder::__construct(), 1 passed in /home/bianchi/webapps/bianchidev/bianchi/app/code/Interjar/ConfigurableChildVisibility/Plugin/Model/ResourceModel/Attribute/InStockOptionSelectBuilder.php on line 34 and exactly 2 expected [] 

I think some modifications in the core of M2 broke on this version.

Please, take a look.

Graziano

**Comment by adamj88** [comment]
Resolved in #19
