### ISSUE TITLE
Errors during compilation (v1.0.0)

### ISSUE THREAD

**Issue by Stevie-Ray** [interjar/configurable-child-visibility#20]
Errors during compilation:                                                   
  	Interjar\ConfigurableChildVisibility\Plugin\Model\ResourceModel\Attribute\  
  InStockOptionSelectBuilder                                                   
  		Extra parameters passed to parent construct: $stockConfiguration.

**Comment by adamj88** [comment]
@Stevie-Ray which version of Magento are you on? The change was introduced for #17 for compatibility with Magento 2.3.4 onwards..

You should be able to continue using v0.6.5 this module for earlier versions.

**Comment by Stevie-Ray** [comment]
@adamj88 thanks for the quick reply, i've switched back to v.6.5 and now it works again (Magento 2.3.3-p1)
