### ISSUE TITLE
Child Out of stock

### ISSUE THREAD

**Issue by Devender93** [interjar/configurable-child-visibility#3]
I use this module it works but the user can click on the option. I want to make it none clickable is this something that is possible with this module I am new to Magento any guidelines will be highly appreciated.

**Comment by adamw1987** [comment]
Hi, I am also looking for it to work like this, with the strikethrough for any sold out options
Thank You

**Comment by Devender93** [comment]
Well I am still finding a way let me know if you found any solution

**Comment by Devender93** [comment]
https://github.com/mjankiewicz/MagentoConfigurableProduct this solve my problem
